name: huge_listview
description: A performant list with any number of items.
version: 1.0.0
homepage: https://github.com/deakjahn/huge_listview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^2.1.3
  scrollable_positioned_list: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

flutter:
